# netlify.toml
[[headers]]
  for = "/*"  # Aplica a todos los archivos
  [headers.values]
    # Deshabilita el cacheo para evitar problemas en Safari
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/static/*"  # Aplica solo a archivos estáticos
  [headers.values]
    # Permite que los recursos estáticos sean cacheados, pero se actualicen al cambiar
    Cache-Control = "public, max-age=31536000, immutable"
