[[headers]]
  for = "/*"  # Aplica a todos los archivos
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/static/*"  # Aplica solo a archivos estáticos
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"